# Google App Engine configuration for Full Sail Finance Volume Predictor
runtime: python39

# Automatic scaling configuration for cost optimization
automatic_scaling:
  min_instances: 2
  max_instances: 25
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.6

# Resource allocation (MAXIMUM COMPUTE POWER)
resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 20

# Environment variables
env_variables:
  PYTHONUNBUFFERED: "1"
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"

# Health check configuration
readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Network settings
network:
  forwarded_ports:
    - 8080
