# Google Cloud Run configuration for Full Sail Finance Volume Predictor
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: full-sail-volume-predictor
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Cost optimization settings
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        # Auto-scaling settings
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        # Startup probe settings
        run.googleapis.com/startup-cpu-boost: "true"
        # Timeout settings
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/full-sail-volume-predictor:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true
